version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:5000"
    volumes:
      - covid-19-dashboard:/covid-19-dashboard/logs
  redis:
    image: "redis:alpine"
volumes:
  covid-19-dashboard:
    external: true
